1) aggregate functions=summarize data and typically
                       return a single value

In [1]:
import numpy as np
arr1=np.array([[1,2,3,4,5],
               [6,7,8,9,10]])

print(np.sum(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.argmax(arr1))
print(np.argmin(arr1))
print(np.var(arr1))
print(np.std(arr1))
print(np.mean(arr1))



55
1
10
9
0
8.25
2.8722813232690143
5.5


2) selcting a specific axis(direction of operations)

2.1 axis==0 , means goes rows wise works cols wise 

2.2 axis==1 , means goes cols wise works rows wise

In [6]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

print(np.sum(arr,axis=0)) # axis 0 is vertical but moves horizonatally
print(np.sum(arr,axis=1)) # axis 1 is horizaontal but moves vertically
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))
print(np.min(arr,axis=0))
print(np.min(arr,axis=1))
print(np.max(arr,axis=0))
print(np.max(arr,axis=1))
print(np.argmin(arr,axis=0))
print(np.argmin(arr,axis=1))
print(np.argmax(arr,axis=0))
print(np.argmax(arr,axis=1))
print(np.var(arr,axis=0))
print(np.var(arr,axis=1))
print(np.std(arr,axis=0))
print(np.std(arr,axis=1))


[ 7  9 11 13 15]
[15 40]
[3.5 4.5 5.5 6.5 7.5]
[3. 8.]
[1 2 3 4 5]
[1 6]
[ 6  7  8  9 10]
[ 5 10]
[0 0 0 0 0]
[0 0]
[1 1 1 1 1]
[4 4]
[6.25 6.25 6.25 6.25 6.25]
[2. 2.]
[2.5 2.5 2.5 2.5 2.5]
[1.41421356 1.41421356]
