1) scalar arithmatic


In [4]:
# scalar arithmatic
# is used to do basic operations to an array
import numpy as np

arr=np.array([1,2,3])

print(arr+1)
print(arr-2)
print(arr*2)
print(arr/2)
print(arr**5)


[2 3 4]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[  1  32 243]


2. vectorized math functions

In [7]:
# vectorized math func
arr2=np.array([1.01,3.43,2891.21])
print(np.sqrt(arr2))
print(np.floor(arr2))
print(np.ceil(arr2))
print(np.pi)

[ 1.00498756  1.85202592 53.76997303]
[1.000e+00 3.000e+00 2.891e+03]
[2.000e+00 4.000e+00 2.892e+03]
3.141592653589793


In [8]:
# exercise to print the area given the radii
radii=np.array([1,2,3])

print(np.square(radii)*np.pi)

[ 3.14159265 12.56637061 28.27433388]


3) element wise arithmatic


In [9]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)
print(arr2**arr1)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[  4  25 216]


4) comparision operaters


In [14]:
# comparision operaters
scores=np.array([91,22,60,55,89,100])

print(scores==100)
print(scores>60)
print(scores<=60)
scores[scores<=60]=0
print(scores)


[False False False False False  True]
[ True False False False  True  True]
[False  True  True  True False False]
[ 91   0   0   0  89 100]
