1) filtering= refers to the process of selecting elements from an array that match a given condition

In [ ]:
import numpy as np
# 1) boolean indexing -> shape not preserved
ages=np.array([[34,12,45,17,16,65,14,29],
      [19,42,52,98,54,21,10,20]])

teenagers=ages[ages<18] # boolean indexing -> retunred flattened 1D array
adults=ages[(ages>=18) & (ages<65)]

elders=ages[ages>=65]
non_adults=ages[(ages<18) | (ages>=65)]
even_ages=ages[ages%2==0]
odd_ages=ages[ages%2!=0]
print(teenagers)
print(adults)
print(elders)
print(non_adults)
print(even_ages)
print(odd_ages)


[12 17 16 14 10]
[34 45 29 19 42 52 54 21 20]
[65 98]
[12 17 16 65 14 98 10]
[34 12 16 14 42 52 98 54 10 20]
[45 17 65 29 19 21]


2) where function to preserve the shape of a function
 
np.where(condition,value_if_true,value_if_false)

is a lot slower than boolean indexing though 

only use if shape needs to be reserved

In [10]:
ages=np.array([[34,12,45,17,16,65,14,29],
      [19,42,52,98,54,21,10,20]])

ages[ages<=18]=0 # updates the original array
adults=np.where((ages>=18)& (ages<65),ages,-1) # creates a copy of origna arr with 
                                               # given updates
print(ages)
print(adults)

[[34  0 45  0  0 65  0 29]
 [19 42 52 98 54 21  0 20]]
[[34 -1 45 -1 -1 -1 -1 29]
 [19 42 52 -1 54 21 -1 20]]
