1) reverse an array

In [ ]:
import numpy as np
arr=np.arange(12).reshape(3,4)
print(arr)
print(np.flip(arr,axis=0))
print(np.flip(arr,axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


specific row or col reverse

In [9]:
arr[2]=np.flip(arr[2])
print(arr)
arr[:,1]=np.flip(arr[:,1])
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [11 10  9  8]]
[[ 0 10  2  3]
 [ 4  5  6  7]
 [11  1  9  8]]


flattening an array

In [15]:
ones=np.ones((2,2,2),dtype=int)
print(ones)
print(ones.flatten())

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[1 1 1 1 1 1 1 1]


ravel method 

changes are in place


In [ ]:
ones=np.ones((2,2,2),dtype=int)
# print(ones)
new_ones=ones.ravel()
new_ones[0]=999
print(ones)
print(new_ones)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[[999   1]
  [  1   1]]

 [[  1   1]
  [  1   1]]]
[999   1   1   1   1   1   1   1]
