In [5]:
print("hello")
print("jupyter is op")
import numpy as np

hello
jupyter is op


control +enter as run shortcut


In [ ]:
# slicing
arr=np.array([[1, 2 ,3 ,4],
             [5, 6 ,7 ,8],
             [9, 10,11,12],
             [13,14,15,16]])
#print(arr[-1:-5:-1])
print(arr[:,2])
print(arr[:-1])


# we can selct multiple columc and rows at once
print(arr[0:3,:2]) # order row,col,
                   # (row_start:row end,col_start:col_end)
# step is tricky it can be set for both the rows and cols

print("eg")
print(arr[0:3:1,1::2])

print(arr[::,3::-1])


[ 3  7 11 15]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
eg
[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [38]:
# index and columns selection at once
print(arr[0:2:1,0:2:1])
print(arr[0:2,2:])
print(arr[2:,:2])
print(arr[2:4:1,2:4:1])

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[ 9 10]
 [13 14]]
[[11 12]
 [15 16]]
