important functions 

zeroes functions

In [9]:
import numpy as np
arr=np.zeros((2,2,10))
print(arr)
# ones function
arr=np.ones((1,2,3)) # layers,rows,cols
print(arr)


[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


2) full functions

In [16]:
arr=np.full((2,3,4),9)
print(arr)
# identity function
arr=np.eye(3)
print(arr)
# empty function
arr=np.empty((2,3))
print(arr)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


3) arrange function
<br>arange(start , stop,step)

In [30]:
arr=np.arange(0,101,2.5) # arange(start , stop ,step)
print(arr)
arr=np.linspace(0,10,20) # start,stop,step
print(arr)

[  0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5  25.   27.5
  30.   32.5  35.   37.5  40.   42.5  45.   47.5  50.   52.5  55.   57.5
  60.   62.5  65.   67.5  70.   72.5  75.   77.5  80.   82.5  85.   87.5
  90.   92.5  95.   97.5 100. ]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
