1) random used for generating random numbers 

used for test cases and others


random(start,end,size)

In [ ]:
import numpy as np
# rng =Random Number Generater
rng=np.random.default_rng(seed=1)
arr=rng.integers(low=1,high=101,size=(4,4))
print(arr)

[[46 36 46 56]
 [42 26 73 20]
 [51 70 29  3]
 [ 5 27 55 95]]


2) uniform


In [5]:
np.random.seed(seed=1)
print(np.random.uniform(low=-1,high=1,size=(3)))

[-0.16595599  0.44064899 -0.99977125]


3) shuffling arrays

In [ ]:
rng=np.random.default_rng()# seed=1
arr=[1,2,3,4,5]
rng.shuffle(arr)
print(arr)

[5, 1, 2, 3, 4]


4) choice


In [15]:
fruits=np.array(["apple","banana","pineapple","orange","strawberry"])
rng=np.random.default_rng()
fruit=rng.choice(fruits,size=(3,2))
print(fruit)

[['orange' 'apple']
 ['banana' 'apple']
 ['pineapple' 'pineapple']]
