1) reshape function->reshape(layer,row,col)

to reshape the row * col of original array should be equal to rows_new * col_new of new array 

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)
arr=arr.reshape(2,6) 
print(arr)
arr=arr.reshape(3,4)
print(arr)
arr=arr.reshape(2,2,3)
print(arr)


(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



-1 takes the most valid value possible if one of the dimensions is fixed

it fills itself

In [11]:

arr=arr.reshape(-1,4) 
print(arr)
arr=arr.reshape(4,-1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
